import tkinter

arduinoConsts = {"SERVO_DELAY": 9, "STEPPER_DELAY": 50, "STEPPER_HORIZONTAL_MOVE": 5, "GRADUAL_INDEX": 64, "DEBOUNCE_DELAY": 30, "COIL_STARTER_POSITION": 1530, "SERVO_ROTATION": 400, "LAYER_TURNS": 436, "COIL_LAYERS": 4}